name: YAML Duplicate Validator CI

on:
  pull_request:
    paths:
      - 'yaml-duplicate-validator.py'
      - 'duplicate_script_tester.py'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  test-validator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run duplicate policy tests
        run: |
          python3 duplicate_script_tester.py
